name: todo_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg_provider: ^1.0.7
  get: ^4.6.6
  iconsax: ^0.0.8
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Icons/
    - assets/Images/
