// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALtRUr9D8JGHzBx99G2VtK3Q4_V-ChjVg',
    appId: '1:93667875046:web:ed10657b2986f24b60c327',
    messagingSenderId: '93667875046',
    projectId: 'todo-app-acf42',
    authDomain: 'todo-app-acf42.firebaseapp.com',
    storageBucket: 'todo-app-acf42.appspot.com',
    measurementId: 'G-YF9LYY4J26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Z_hp2f8H1sISqmtbaWYBsF_CBPxWCYo',
    appId: '1:93667875046:android:4e6fd1cb9df4461e60c327',
    messagingSenderId: '93667875046',
    projectId: 'todo-app-acf42',
    storageBucket: 'todo-app-acf42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqMs-SHw1Pj7tkbjaps_NoePsO3zA4MPU',
    appId: '1:93667875046:ios:116674db3006855560c327',
    messagingSenderId: '93667875046',
    projectId: 'todo-app-acf42',
    storageBucket: 'todo-app-acf42.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqMs-SHw1Pj7tkbjaps_NoePsO3zA4MPU',
    appId: '1:93667875046:ios:bb1c8a6bd1daecae60c327',
    messagingSenderId: '93667875046',
    projectId: 'todo-app-acf42',
    storageBucket: 'todo-app-acf42.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
